my:
    resource: "@MyBundle/Controller/"
    type:     annotation
    prefix:   /

my_another:
    resource: "@MyAnotherBundle/Controller/"
    type:     annotation
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
